[project]
name = "aoc-quick-templater"
version = "0.1.0"
description = "Templates AoC problem in python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["httpx>=0.28.0", "jinja2>=3.1.4", "typer>=0.14.0"]

[dependency-groups]
dev = ["mypy>=1.13.0"]
